### ISSUE TITLE
Error immediately after installation

### ISSUE THREAD

**Issue by Arberto99** [deinsoftware/swpm#22]
## Prerequisites

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
Init an existing package manager.

## Current Behavior
I'm trying to switch my Angular project from npm to pnpm, so I downloaded this.
I've installed it, with no errors, and as soon I run the first command it gives me this error:

`$ swpm init npm
🔒 npm init npm
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'init', 'npm' ]
}

Node.js v18.13.0
`

Or, if I try other commands like "swpm test" the error changes in:
`$ swpm test
🔒 npm test
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'test' ]
}

Node.js v18.13.0
`

### Steps to Reproduce

1. I've installed it with command "npm install swpm --location=global" on an existing Angular project, and it gives me no error
2. I've tried to run some commands and everytime I got the error above.

### Context

- swpm Version: 1.0.1
- node Version: 18.13.0
- Package Manager: npm
- Package Manager Version: 9.4.0
- Operating System: Windows 11
- Angular CLI project version: 14.2.10

Thanks a lot!

**Comment by equiman** [comment]
Could you please run the command: `swpm --info` and show the result here?

**Comment by Arberto99** [comment]
> Could you please run the command: `swpm --info` and show the result here?

That's what I get when i run swpm --info:
```
$ swpm --info
using:  npm 
origin: 🔒 lock

Versions:
swpm:   1.0.2
Node:   18.13.0
npm:    8.19.3
```

> Are you running those commands inside the `angular` project path?

Yes, of course.
 
> What's the result of running these commands `node --version` and `npm --version`?

```
$ node --version
v18.13.0

```

```
$ npm --version
8.19.3

```

**Comment by equiman** [comment]
What happens if you run the commands directly with `npm`?

`npm init npm`

`npm test`

**Comment by equiman** [comment]
Seems to be that is something related to the PATH:
https://stackoverflow.com/a/37366944/812915

I'll try to do some tests and I tell you when a new version is available for testing.

**Comment by equiman** [comment]
Try installing this version: `npm install swpm@1.0.3-beta.1 --location=global` and test running the commands again.

**Comment by Arberto99** [comment]
Hi!
I've installed swpm@1.0.3-beta.1 and now I got this:

```
$ swpm init npm
🔒 npm init npm


Usage: GITHUB_TOKEN=? NPM_TOKEN=? yarn create user/repo
```

And this:

```
$ swpm test
🔒 npm test

> @my-app/my-app@2.0.43 test
> ng test

✔ Browser application bundle generation complete.
...
...

```

Now it seems to work properly.
Thanks a lot, I appreciate what you did! ;)

**Comment by equiman** [comment]
Excellent news. I'll try to release this version as stable tonight.

Thanks for reporting it and for your help.

**Comment by equiman** [comment]
New version is available:
`npm install swpm@latest --location=global`
