### ISSUE TITLE
error when running `sx nx@latest init`

### ISSUE THREAD

**Issue by ptandler** [deinsoftware/swpm#64]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
```bash
❯ volta install swpm
success: installed swpm@1.10.6 with executables: swpm, ...
```

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

sx nx@latest should download and run nx

## Current Behavior

What is the current behavior?

The command that sx outputs looks fine to me, but running it fails. However, when I run the command written by sx, this works well:

```bash
❯ sx nx@latest init
📌 pnpm dlx nx@latest init
Error:
Error: spawn pnpm dlx ENOENT


❯ pnpm dlx nx@latest init
.../share/pnpm/store/v3/tmp/dlx-186352   | +124 ++++++++++++
.../share/pnpm/store/v3/tmp/dlx-186352   | Progress: resolved 132, reused 124, downloaded 0, added 124, done
../../../../.local/share/pnpm/store/v3/tmp/dlx-186352/node_modules/.pnpm/@parcel+watcher@2.0.4/node_modules/@parcel/watcher: Running install script, done in 98ms
.../share/pnpm/store/v3/tmp/dlx-186352   |  WARN  An error occurred while uploading /home/ptandler/.local/share/pnpm/store/v3/tmp/dlx-186352/node_modules/.pnpm/@parcel+watcher@2.0.4/node_modules/@parcel/watcher
../../../../.local/share/pnpm/store/v3/tmp/dlx-186352/node_modules/.pnpm/nx@16.3.2/node_modules/nx: Running postinstall script, done in 248ms
.../share/pnpm/store/v3/tmp/dlx-186352   |  WARN  An error occurred while uploading /home/ptandler/.local/share/pnpm/store/v3/tmp/dlx-186352/node_modules/.pnpm/nx@16.3.2/node_modules/nx

 >  NX   🧐 Checking versions compatibility
...
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- swpm Version: swpm@1.10.6
- node Version: v18.16.0
- Package Manager: `pnpm`
- Package Manager Version: 8.6.0
- Operating System:  Linux, Kernel: 5.15.0-73-generic x86_64 bits: 64, Distro: Linux Mint 20.3 Una

**Comment by equiman** [comment]
Thanks for reporting it. It was fixed on version [1.10.7](https://github.com/deinsoftware/swpm/releases/tag/v1.10.7), please update it and let me know if it works.

**Comment by ptandler** [comment]
wow, that was quick fixing it! I can confirm that it now works with 1.10.7. Thanks! :+1: 
You're going to mark it as "latest" version?

**Comment by equiman** [comment]
Excellent!

Yes, I'll promote it as the "latest" version. 

Thanks!
