### ISSUE TITLE
Global pins?

### ISSUE THREAD

**Issue by bernardoadc** [deinsoftware/swpm#7]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked to make sure that this command request has not already been filed

## Command to add

This is first a doubt, more than an addition. Does the pin command work only for current project or is there a way to "pin it globally"? If both are available, this would mean that having pnpm pinned globally would automatically work for any project. But if some project has pinned npm, then that would be preferred in it.

## Expected Result

```shell
swpm --pin --global pnpm
mkdir someproject
cd someproject
swpm install # will use pnpm automatically
```

### Context

I'm learning the tool first. If anything, this should help improve the docs.

**Comment by equiman** [comment]
Hi @bernardoadc there is no global pin command. But you can set a package manager by default with an environment variable.

It is documented on this link.

https://github.com/deinsoftware/swpm#use 

Let me know if this solves your doubt.

**Comment by equiman** [comment]
I've created a new section on readme (and menu) to easy access.

https://github.com/deinsoftware/swpm#default

**Comment by equiman** [comment]
It can't be created or updated with OS environment variables directly with node.js.
https://nodejs.org/api/process.html#process_process_env

So, it will need to be set manually as described on the readme.

**Comment by bernardoadc** [comment]
great @equiman ! Sorry for the late response.

I believe it should have a way of setting it with spawn (I think package cross-env does that), but setting the variable manually is equally fine!

**Comment by equiman** [comment]
Thanks for the recommendation, I will take a look before finishing a new feature about aliases.

https://www.npmjs.com/package/cross-env
